networks:
  sentinel-frontend-network:
    external: true
    name: sentinel-frontend-network
  sentinel-backend-network:
    external: true
    name: sentinel-backend-network

services:
  nats:
    image: nats:latest
    container_name: sentinel-nats
    ports:
      - "4222:4222"
      - "8222:8222" # Monitoring port
    volumes:
      - nats-data:/data/nats
    command:
      - "--name=nats"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data/nats"

    restart: unless-stopped
    networks:
      - sentinel-backend-network

  nats-dashboard:
    image: mdawar/nats-dashboard
    container_name: nats-dashboard
    restart: unless-stopped
    environment:
      # The NATS monitoring server will be proxied on /proxy/* on the frontend.
      # See: config/Caddyfile for the reverse proxy configuration.
      REVERSE_PROXY_UPSTREAM: 'nats:8222'
#    volumes:
#      - ${CONFIG_PATH}/nats/nats-config.json:/srv/config.json
    ports:
      - "8502:80"
    networks:
      - sentinel-frontend-network
      - sentinel-backend-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: sentinel-qdrant
    ports:
      - "6333:6333" # Web UI
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped
    networks:
      - sentinel-backend-network

  postgres:
    image: postgres:16
    container_name: sentinel-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s # Increased start_period
    restart: unless-stopped
    networks:
      - sentinel-backend-network

  pgadmin:
    container_name: pgadmin #not adding this cause yugabyte health check not to start
    image: dpage/pgadmin4:9.4.0
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin@pgadmin.com'
      PGADMIN_DEFAULT_PASSWORD: 'pgadmin'
    ports:
      - 16543:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - sentinel-backend-network
      - sentinel-frontend-network
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:80/misc/ping" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  nats-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/nats
  qdrant-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/qdrant
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/postgres