version: '3.8'

networks:
  frontend-network:
    external: true
    name: frontend-network

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: sentinel-portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "${PORTAINER_PORT}:9000"
    restart: unless-stopped
    networks:
      - frontend-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=PathPrefix(`/portainer`)"
      - "traefik.http.middlewares.portainer-stripprefix.stripprefix.prefixes=/portainer"
      - "traefik.http.routers.portainer.middlewares=portainer-stripprefix"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/portainer
